"""
Unit tests for Enhanced HTML Report generation.
"""

import pytest
from primerlab.core.report.html_enhanced import (
    HTMLReportGenerator,
    ReportSection,
    ReportData,
    generate_html_report,
)


class TestReportSection:
    """Tests for ReportSection model."""
    
    def test_creation(self):
        """Test ReportSection creation."""
        section = ReportSection(
            title="Summary",
            content="<p>Test content</p>",
            section_type="text",
        )
        
        assert section.title == "Summary"
        assert section.content == "<p>Test content</p>"


class TestReportData:
    """Tests for ReportData model."""
    
    def test_creation(self):
        """Test ReportData creation."""
        data = ReportData(
            title="Test Report",
            subtitle="Test Subtitle",
        )
        
        assert data.title == "Test Report"
        assert data.sections == []


class TestHTMLReportGenerator:
    """Tests for HTMLReportGenerator."""
    
    def test_generator_creation(self):
        """Test generator creation."""
        generator = HTMLReportGenerator()
        assert generator.config == {}
    
    def test_generate_basic_report(self):
        """Test basic report generation."""
        generator = HTMLReportGenerator()
        
        data = ReportData(
            title="Test Report",
            subtitle="Generated by tests",
            sections=[
                ReportSection(title="Section 1", content="<p>Content</p>"),
            ],
        )
        
        html = generator.generate(data)
        
        assert "<!DOCTYPE html>" in html
        assert "Test Report" in html
        assert "Section 1" in html
    
    def test_create_table(self):
        """Test table creation."""
        generator = HTMLReportGenerator()
        
        headers = ["Name", "Value"]
        rows = [
            ["Item 1", "100"],
            ["Item 2", "200"],
        ]
        
        table = generator.create_table(headers, rows)
        
        assert "<table>" in table
        assert "<th>Name</th>" in table
        assert "<td>Item 1</td>" in table
    
    def test_create_metrics(self):
        """Test metrics cards creation."""
        generator = HTMLReportGenerator()
        
        metrics = {
            "Score": 85,
            "Grade": "A",
        }
        
        html = generator.create_metrics(metrics)
        
        assert "metric-grid" in html
        assert "85" in html
        assert "Score" in html
    
    def test_create_badge(self):
        """Test badge creation."""
        generator = HTMLReportGenerator()
        
        badge = generator.create_badge("Success", "success")
        
        assert "badge-success" in badge
        assert "Success" in badge


class TestGenerateHTMLReport:
    """Tests for generate_html_report function."""
    
    def test_function_call(self):
        """Test function call."""
        result_data = {
            "primers": {
                "forward": {"sequence": "ATGCATGC", "tm": 60.0, "gc": 50.0},
                "reverse": {"sequence": "GCATGCAT", "tm": 59.5, "gc": 50.0},
            },
            "amplicons": [{"length": 250}],
            "qc": {"quality_score": 85, "quality_category": "B"},
        }
        
        html = generate_html_report("Test Report", result_data)
        
        assert "<!DOCTYPE html>" in html
        assert "Test Report" in html
        assert "ATGCATGC" in html
    
    def test_empty_result(self):
        """Test with empty result data."""
        html = generate_html_report("Empty Report", {})
        
        assert "<!DOCTYPE html>" in html
        assert "Empty Report" in html
