"""
Species Specificity Report Generation.

Generates Markdown, JSON, and Excel reports for species specificity analysis.
"""

import json
import logging
from pathlib import Path
from typing import Dict, Any

from .models import SpeciesCheckResult
from .scoring import generate_specificity_matrix_table

logger = logging.getLogger(__name__)


def generate_species_json_report(result: SpeciesCheckResult, output_dir: str) -> str:
    """Generate JSON report for species specificity check."""
    output_path = Path(output_dir) / "species_analysis.json"
    
    with open(output_path, "w") as f:
        json.dump(result.to_dict(), f, indent=2)
    
    logger.info(f"JSON report saved to {output_path}")
    return str(output_path)


def generate_species_markdown_report(result: SpeciesCheckResult, output_dir: str) -> str:
    """Generate Markdown report for species specificity check."""
    output_path = Path(output_dir) / "species_report.md"
    
    grade_color = {
        "A": "🟢", "B": "🟢", 
        "C": "🟡", "D": "🟠", "F": "🔴"
    }.get(result.grade, "⚪")

    lines = [
        "# Species Specificity Report",
        "",
        f"**Target Species:** {result.target_species}",
        f"**Primers Analyzed:** {result.primers_checked}",
        f"**Species Checked:** {result.species_checked}",
        "",
        "## 📊 Score Overview",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| **Overall Score** | **{result.overall_score:.1f}/100** |",
        f"| **Grade** | {grade_color} **{result.grade}** |",
        f"| **Status** | {'✅ Specific' if result.is_specific else '⚠️ Cross-Reactive'} |",
        "",
    ]
    
    # Warnings
    if result.warnings:
        lines.append("## ⚠️ Warnings")
        lines.append("")
        for w in result.warnings:
            lines.append(f"- {w}")
        lines.append("")
    
    # Recommendations
    if result.recommendations:
        lines.append("## 💡 Recommendations")
        lines.append("")
        for r in result.recommendations:
            lines.append(f"- {r}")
        lines.append("")
    
    # Specificity Matrix
    lines.append("## 📋 Specificity Matrix")
    lines.append("")
    lines.append("```")
    lines.append(generate_specificity_matrix_table(result.specificity_matrix))
    lines.append("```")
    lines.append("")
    
    lines.append("---")
    lines.append("*Generated by PrimerLab v0.4.2*")
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    
    logger.info(f"Markdown report saved to {output_path}")
    return str(output_path)


def generate_species_excel_report(result: SpeciesCheckResult, output_dir: str) -> str:
    """
    Generate Excel report for species specificity check.
    
    Sheets:
    - Summary: Score, grade, status
    - Matrix: Specificity matrix
    - Warnings: List of warnings
    """
    try:
        import openpyxl
        from openpyxl.styles import Font, PatternFill
    except ImportError:
        logger.warning("openpyxl not installed. Run: pip install openpyxl")
        return None
    
    output_path = Path(output_dir) / "species_analysis.xlsx"
    wb = openpyxl.Workbook()
    
    header_fill = PatternFill(start_color="4472C4", end_color="4472C4", fill_type="solid")
    header_font = Font(bold=True, color="FFFFFF")
    target_fill = PatternFill(start_color="51CF66", end_color="51CF66", fill_type="solid")
    warn_fill = PatternFill(start_color="FF6B6B", end_color="FF6B6B", fill_type="solid")
    
    # --- Summary Sheet ---
    ws = wb.active
    ws.title = "Summary"
    
    summary_data = [
        ["Species Specificity Report", ""],
        ["", ""],
        ["Metric", "Value"],
        ["Target Species", result.target_species],
        ["Overall Score", f"{result.overall_score:.1f}/100"],
        ["Grade", result.grade],
        ["Status", "Specific" if result.is_specific else "Cross-Reactive"],
        ["Primers Checked", result.primers_checked],
        ["Species Checked", result.species_checked],
    ]
    
    for row_idx, row_data in enumerate(summary_data, 1):
        for col_idx, value in enumerate(row_data, 1):
            cell = ws.cell(row=row_idx, column=col_idx, value=value)
            if row_idx == 1:
                cell.font = Font(bold=True, size=14)
            elif row_idx == 3:
                cell.fill = header_fill
                cell.font = header_font
    
    ws.column_dimensions['A'].width = 20
    ws.column_dimensions['B'].width = 25
    
    # --- Matrix Sheet ---
    ws_matrix = wb.create_sheet("Specificity Matrix")
    
    matrix = result.specificity_matrix
    
    # Header row
    ws_matrix.cell(row=1, column=1, value="Primer")
    for col_idx, species in enumerate(matrix.species_names, 2):
        cell = ws_matrix.cell(row=1, column=col_idx, value=species)
        cell.fill = header_fill if species != matrix.target_species else target_fill
        cell.font = header_font
    
    # Data rows
    for row_idx, primer in enumerate(matrix.primer_names, 2):
        ws_matrix.cell(row=row_idx, column=1, value=primer)
        
        for col_idx, species in enumerate(matrix.species_names, 2):
            binding = matrix.get_binding(primer, species)
            if binding and binding.has_binding:
                pct = binding.best_match_percent
                cell = ws_matrix.cell(row=row_idx, column=col_idx, value=f"{pct:.0f}%")
                if species != matrix.target_species and pct >= 80:
                    cell.fill = warn_fill
            else:
                ws_matrix.cell(row=row_idx, column=col_idx, value="-")
    
    # --- Warnings Sheet ---
    if result.warnings:
        ws_warn = wb.create_sheet("Warnings")
        ws_warn.cell(row=1, column=1, value="Warning").font = Font(bold=True)
        for row_idx, warning in enumerate(result.warnings, 2):
            ws_warn.cell(row=row_idx, column=1, value=warning)
        ws_warn.column_dimensions['A'].width = 80
    
    wb.save(output_path)
    logger.info(f"Excel report saved to {output_path}")
    return str(output_path)
