from typing import Dict, Any
from primerlab.core.models import WorkflowResult

class ReportGenerator:
    """
    Generates a Markdown report for PCR/qPCR workflow results.
    """
    
    def generate_report(self, result: WorkflowResult) -> str:
        """
        Converts WorkflowResult into a Markdown string.
        """
        md = []
        
        # 1. Header
        md.append(f"# PrimerLab Report: {result.workflow.upper()}")
        md.append(f"**Date:** {result.metadata.timestamp}")
        md.append(f"**Version:** {result.metadata.version}")
        md.append("")
        
        # 2. Input Summary
        md.append("## 1. Input Summary")
        params = result.metadata.parameters
        md.append(f"- **Target Tm:** {params.get('tm', {}).get('opt')}°C")
        md.append(f"- **Target Size:** {params.get('primer_size', {}).get('opt')} bp")
        if "probe" in params:
             md.append(f"- **Probe Tm:** {params.get('probe', {}).get('tm', {}).get('opt')}°C")
        md.append("")

        # 3. Primer Results
        md.append("## 2. Best Primer Set")
        
        if not result.primers:
            md.append("> **No valid primers found.**")
            return "\n".join(md)

        fwd = result.primers.get("forward")
        rev = result.primers.get("reverse")
        probe = result.primers.get("probe")
        
        # Table for Primers
        cols = ["Property", "Forward Primer", "Reverse Primer"]
        if probe:
            cols.append("Probe")
            
        header = "| " + " | ".join(cols) + " |"
        separator = "| " + " | ".join([":---"] * len(cols)) + " |"
        
        md.append(header)
        md.append(separator)
        
        def row(label, f_val, r_val, p_val=None):
            r = f"| **{label}** | {f_val} | {r_val} |"
            if probe:
                r += f" {p_val} |"
            return r

        md.append(row("ID", f"`{fwd.id}`", f"`{rev.id}`", f"`{probe.id}`" if probe else ""))
        md.append(row("Sequence", f"`{fwd.sequence}`", f"`{rev.sequence}`", f"`{probe.sequence}`" if probe else ""))
        md.append(row("Length", f"{fwd.length} bp", f"{rev.length} bp", f"{probe.length} bp" if probe else ""))
        md.append(row("Tm", f"{fwd.tm:.2f}°C", f"{rev.tm:.2f}°C", f"{probe.tm:.2f}°C" if probe else ""))
        md.append(row("GC", f"{fwd.gc:.1f}%", f"{rev.gc:.1f}%", f"{probe.gc:.1f}%" if probe else ""))
        md.append(row("Position", f"{fwd.start}", f"{rev.start}", f"{probe.start}" if probe else ""))
        md.append("")
        
        # 4. Amplicon Info
        if result.amplicons:
            amp = result.amplicons[0]
            md.append("### Amplicon Details")
            md.append(f"- **Product Size:** {amp.length} bp")
            md.append(f"- **Position:** {amp.start} - {amp.end}")
            md.append("")

        # 5. QC Evaluation
        md.append("## 3. QC Evaluation")
        if result.qc:
            qc = result.qc
            
            # Status Badge
            status = "✅ PASS" if not qc.warnings and not qc.errors else "⚠️ WARNING"
            if qc.errors: status = "❌ FAIL"
            
            md.append(f"**Overall Status:** {status}")
            md.append("")
            
            md.append("| Metric | Value | Status |")
            md.append("| :--- | :--- | :--- |")
            md.append(f"| **Tm Difference** | {qc.tm_diff:.2f}°C | {'✅' if qc.tm_balance_ok else '⚠️'} |")
            md.append(f"| **Hairpin ΔG** | {qc.hairpin_dg:.2f} | {'✅' if qc.hairpin_ok else '⚠️'} |")
            md.append(f"| **Homodimer ΔG** | {qc.homodimer_dg:.2f} | {'✅' if qc.homodimer_ok else '⚠️'} |")
            
            if qc.warnings:
                md.append("")
                md.append("### Warnings")
                for w in qc.warnings:
                    md.append(f"- ⚠️ {w}")
        else:
            md.append("QC data not available.")
        
        md.append("")
        md.append("---")
        md.append("*Generated by PrimerLab*")
        
        return "\n".join(md)
