"""
Tm Gradient Report Generation.

Generate reports in various formats for Tm gradient simulation results.
"""

from typing import List, Dict, Any
from pathlib import Path


def generate_tm_gradient_markdown(
    results: List[Dict],
    optimal: Dict,
    config: Dict,
    output_path: str
) -> str:
    """
    Generate markdown report for Tm gradient simulation.
    
    Args:
        results: List of primer result dicts
        optimal: Optimal annealing temperature dict
        config: Gradient config dict
        output_path: Output file path
        
    Returns:
        Path to created markdown file
    """
    lines = [
        "# Tm Gradient Simulation Report",
        "",
        "## Configuration",
        "",
        f"- **Temperature Range**: {config['min_temp']}°C - {config['max_temp']}°C",
        f"- **Step Size**: {config['step_size']}°C",
        "",
        "## Optimal Annealing Temperature",
        "",
        f"🎯 **Recommended Temperature**: **{optimal['optimal']:.1f}°C**",
        "",
        f"| Parameter | Value |",
        f"|-----------|-------|",
        f"| Optimal | {optimal['optimal']:.1f}°C |",
        f"| Range Min | {optimal['range_min']:.1f}°C |",
        f"| Range Max | {optimal['range_max']:.1f}°C |",
        "",
        "## Per-Primer Results",
        "",
        "| Primer | Tm (°C) | Optimal Annealing | Grade |",
        "|--------|---------|-------------------|-------|",
    ]

    for r in results:
        lines.append(
            f"| {r['primer_name']} | {r['calculated_tm']:.1f} | "
            f"{r['optimal_annealing_temp']:.1f} | {r['grade']} |"
        )

    lines.extend([
        "",
        "## Grade Legend",
        "",
        "| Grade | Score Range | Interpretation |",
        "|-------|-------------|----------------|",
        "| A | ≥90 | Excellent - wide temperature tolerance |",
        "| B | 80-89 | Good - stable across range |",
        "| C | 70-79 | Acceptable - moderate sensitivity |",
        "| D | 60-69 | Poor - narrow window |",
        "| F | <60 | Fail - redesign recommended |",
        "",
        "---",
        "",
        "*Generated by PrimerLab v0.4.3*",
    ])

    path = Path(output_path)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return str(path)


def generate_tm_gradient_csv(
    results: List[Dict],
    optimal: Dict,
    config: Dict,
    output_path: str
) -> str:
    """
    Generate CSV report for Tm gradient simulation.
    
    Args:
        results: List of primer result dicts
        optimal: Optimal annealing temperature dict
        config: Gradient config dict
        output_path: Output file path
        
    Returns:
        Path to created CSV file
    """
    lines = [
        "Primer,Calculated_Tm,Optimal_Annealing,Grade,Score"
    ]

    for r in results:
        lines.append(
            f"{r['primer_name']},{r['calculated_tm']:.1f},"
            f"{r['optimal_annealing_temp']:.1f},{r['grade']},{r.get('score', 0):.1f}"
        )

    # Add summary
    lines.extend([
        "",
        "# Summary",
        f"Optimal_Temperature,{optimal['optimal']:.1f}",
        f"Range_Min,{optimal['range_min']:.1f}",
        f"Range_Max,{optimal['range_max']:.1f}",
        f"Config_Min_Temp,{config['min_temp']}",
        f"Config_Max_Temp,{config['max_temp']}",
        f"Config_Step,{config['step_size']}",
    ])

    path = Path(output_path)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return str(path)
