"""
Specificity Report Generator (v0.3.0)

Generates human-readable reports for off-target analysis.
"""

from pathlib import Path
from typing import Union
from datetime import datetime

from primerlab.core.offtarget.finder import OfftargetResult, PrimerPairOfftargetResult
from primerlab.core.offtarget.scorer import SpecificityScore


def generate_specificity_report(
    result: Union[OfftargetResult, PrimerPairOfftargetResult],
    score: SpecificityScore,
    output_dir: Path
) -> Path:
    """
    Generate markdown report for specificity analysis.
    
    Args:
        result: Off-target analysis result
        score: Specificity score
        output_dir: Output directory
        
    Returns:
        Path to generated report
    """
    lines = []
    
    # Header
    lines.append("# 🎯 Primer Specificity Report")
    lines.append("")
    lines.append(f"*Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*")
    lines.append("")
    
    # Score Summary
    lines.append("## Summary")
    lines.append("")
    lines.append(f"| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| **Overall Score** | {score.overall_score:.1f} |")
    lines.append(f"| **Grade** | {score.grade} |")
    lines.append(f"| **Status** | {'✅ Specific' if score.is_acceptable else '⚠️ Low Specificity'} |")
    lines.append("")
    
    # Score breakdown
    lines.append("### Score Breakdown")
    lines.append("")
    lines.append(f"| Component | Score |")
    lines.append("|-----------|-------|")
    lines.append(f"| Binding | {score.binding_score:.1f} |")
    lines.append(f"| Mismatch | {score.mismatch_score:.1f} |")
    lines.append(f"| Products | {score.product_score:.1f} |")
    lines.append("")
    
    # Primer pair results
    if isinstance(result, PrimerPairOfftargetResult):
        lines.append("## Forward Primer")
        lines.append("")
        _add_primer_section(lines, result.forward_result)
        
        lines.append("## Reverse Primer")
        lines.append("")
        _add_primer_section(lines, result.reverse_result)
        
        if result.potential_products > 0:
            lines.append("## ⚠️ Potential Off-target Products")
            lines.append("")
            lines.append(f"**{result.potential_products}** potential off-target product(s) detected")
            lines.append("(sequences where both primers could bind)")
            lines.append("")
    else:
        lines.append("## Primer Analysis")
        lines.append("")
        _add_primer_section(lines, result)
    
    # Warnings
    warnings = []
    if isinstance(result, PrimerPairOfftargetResult):
        warnings = result.warnings
    elif hasattr(result, 'warnings'):
        warnings = result.warnings
    
    if warnings:
        lines.append("## ⚠️ Warnings")
        lines.append("")
        for w in warnings:
            lines.append(f"- {w}")
        lines.append("")
    
    # Footer
    lines.append("---")
    lines.append("")
    lines.append("*Report generated by PrimerLab v0.3.0*")
    
    # Write file
    output_path = output_dir / "specificity_report.md"
    with open(output_path, "w") as f:
        f.write("\n".join(lines))
    
    return output_path


def _add_primer_section(lines: list, result: OfftargetResult):
    """Add primer-specific section to report."""
    lines.append(f"**Sequence:** `{result.primer_seq}`")
    lines.append("")
    
    if result.target_id:
        lines.append(f"**Target:** {result.target_id}")
        lines.append(f"**On-target found:** {'✅ Yes' if result.on_target_found else '❌ No'}")
        lines.append("")
    
    lines.append(f"| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Off-targets | {result.offtarget_count} |")
    lines.append(f"| Significant | {result.significant_offtargets} |")
    lines.append(f"| Score | {result.specificity_score:.1f} |")
    lines.append("")
    
    # Off-target details
    if result.offtargets:
        lines.append("### Off-target Sites")
        lines.append("")
        lines.append("| Sequence | Position | Identity | Risk |")
        lines.append("|----------|----------|----------|------|")
        
        for ot in result.offtargets[:10]:  # Limit to 10
            risk_icon = "🔴" if ot.risk_level == "high" else "🟡" if ot.risk_level == "medium" else "🟢"
            lines.append(f"| {ot.sequence_id[:20]} | {ot.position} | {ot.identity:.1f}% | {risk_icon} {ot.risk_level} |")
        
        if len(result.offtargets) > 10:
            lines.append(f"| ... | *{len(result.offtargets) - 10} more* | | |")
        
        lines.append("")
