"""
Multiplex Analysis Report Generator.
Generates comprehensive reports (JSON/Markdown) for multiplex compatibility analysis.
"""

import json
import logging
from pathlib import Path
from typing import Dict, List, Optional
from datetime import datetime

from .models import MultiplexResult, CompatibilityMatrix

logger = logging.getLogger(__name__)

def generate_json_report(result: MultiplexResult, output_dir: Path) -> Path:
    """Saves validation result as JSON."""
    output_path = output_dir / "multiplex_analysis.json"
    
    with open(output_path, "w") as f:
        json.dump(result.to_dict(), f, indent=2)
        
    logger.info(f"JSON report saved to {output_path}")
    return output_path

def generate_markdown_report(result: MultiplexResult, output_dir: Path) -> Path:
    """Generates a detailed Markdown report for multiplex analysis."""
    output_path = output_dir / "multiplex_report.md"
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    grade_color = {
        "A": "🟢", "B": "🟢", 
        "C": "🟡", "D": "🟠", "F": "🔴"
    }.get(result.grade, "⚪")

    md = [
        f"# Multiplex Compatibility Report",
        f"**Date:** {timestamp}",
        f"**Pairs Analyzed:** {len(result.pairs)}",
        f"**Overall Status:** {'✅ COMPATIBLE' if result.is_valid else '❌ INCOMPATIBLE'}",
        "",
        f"## 📊 Score Overview",
        f"| Metric | Value |",
        f"| :--- | :--- |",
        f"| **Overall Score** | **{result.score:.1f}/100** |",
        f"| **Grade** | {grade_color} **{result.grade}** |",
        "",
        "## 🔬 Component Breakdowns",
        f"- **Dimer Score:** {result.component_scores.get('dimer_score', 0):.1f}/100",
        f"- **Tm Uniformity:** {result.component_scores.get('tm_uniformity', 0):.1f}/100 (Avg Tm: {result.avg_tm:.1f}°C)",
        f"- **GC Uniformity:** {result.component_scores.get('gc_uniformity', 0):.1f}/100 (Avg GC: {result.avg_gc:.1f}%)",
        "",
        "## ⚠️ Issues & Warnings",
    ]
    
    if not result.warnings and not result.errors:
        md.append("No issues detected! 🎉")
    else:
        if result.errors:
            md.append("### ❌ Critical Errors")
            for err in result.errors:
                md.append(f"- {err}")
        
        if result.warnings:
            md.append("### ⚠️ Warnings")
            for warn in result.warnings:
                md.append(f"- {warn}")

    if result.recommendations:
        md.append("")
        md.append("## 💡 Recommendations")
        for rec in result.recommendations:
            md.append(f"- {rec}")
            
    md.append("")
    md.append("## 🧩 Primer Pair Details")
    md.append("| Pair | Fwd Tm | Rev Tm | Fwd GC | Rev GC |")
    md.append("| :--- | :--- | :--- | :--- | :--- |")
    
    for pair in result.pairs:
        md.append(f"| {pair.name} | {pair.tm_forward:.1f}°C | {pair.tm_reverse:.1f}°C | {pair.gc_forward:.1f}% | {pair.gc_reverse:.1f}% |")

    md.append("")
    md.append("---\n*Generated by PrimerLab v0.4.0*")
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(md))
        
    logger.info(f"Markdown report saved to {output_path}")
    return output_path
