from typing import Dict, Any
from primerlab.core.models import WorkflowResult
from primerlab.core.logger import get_logger

logger = get_logger()

class qPCRReportGenerator:
    """
    Generates qPCR-specific reports.
    """
    
    def generate_report(self, result: WorkflowResult) -> str:
        """
        Generates a Markdown report for qPCR workflow results.
        """
        lines = []
        
        # Header
        lines.append("# qPCR Workflow Report")
        lines.append("")
        lines.append(f"**Workflow:** {result.workflow.upper()}")
        lines.append(f"**Timestamp:** {result.metadata.timestamp}")
        lines.append(f"**Version:** {result.metadata.version}")
        lines.append("")
        lines.append("---")
        lines.append("")
        
        # Primers Section
        lines.append("## Primers & Probe")
        lines.append("")
        
        if result.primers:
            for name, primer in result.primers.items():
                lines.append(f"### {name.capitalize()}")
                lines.append(f"- **Sequence:** `{primer.sequence}`")
                lines.append(f"- **Length:** {primer.length} bp")
                lines.append(f"- **Tm:** {primer.tm:.2f}°C")
                lines.append(f"- **GC:** {primer.gc:.1f}%")
                lines.append(f"- **Position:** {primer.start}-{primer.end}")
                lines.append(f"- **Hairpin ΔG:** {primer.hairpin_dg:.2f} kcal/mol")
                lines.append(f"- **Homodimer ΔG:** {primer.homodimer_dg:.2f} kcal/mol")
                lines.append("")
        else:
            lines.append("⚠️ **No primers found**")
            lines.append("")
        
        # Amplicon Section
        lines.append("---")
        lines.append("")
        lines.append("## Amplicon")
        lines.append("")
        
        if result.amplicons:
            amp = result.amplicons[0]
            lines.append(f"- **Size:** {amp.length} bp")
            lines.append(f"- **Position:** {amp.start}-{amp.end}")
            lines.append(f"- **Primer Tm (Fwd/Rev):** {amp.tm_forward:.2f}°C / {amp.tm_reverse:.2f}°C")
            lines.append("")
        else:
            lines.append("⚠️ **No amplicon data**")
            lines.append("")
        
        # qPCR-Specific: Efficiency
        lines.append("---")
        lines.append("")
        lines.append("## qPCR Metrics")
        lines.append("")
        
        if hasattr(result, 'efficiency') and result.efficiency:
            lines.append(f"- **Estimated Efficiency:** {result.efficiency}%")
            if 90 <= result.efficiency <= 110:
                lines.append("  - ✅ Within optimal range (90-110%)")
            elif 80 <= result.efficiency < 90:
                lines.append("  - ⚠️ Lower than ideal (consider optimizing primers)")
            else:
                lines.append("  - ⚠️ Outside typical range")
        else:
            lines.append("- **Estimated Efficiency:** N/A")
        lines.append("")
        
        # QC Section
        lines.append("---")
        lines.append("")
        lines.append("## Quality Control")
        lines.append("")
        
        if result.qc:
            qc = result.qc
            
            # Overall Status
            overall_ok = (qc.hairpin_ok and qc.homodimer_ok and 
                         qc.heterodimer_ok and qc.tm_balance_ok)
            
            if overall_ok:
                lines.append("✅ **Status:** PASS")
            else:
                lines.append("⚠️ **Status:** WARNING")
            
            lines.append("")
            lines.append("### Checks")
            lines.append(f"- Hairpin: {'✅ PASS' if qc.hairpin_ok else '⚠️ FAIL'}")
            lines.append(f"- Homodimer: {'✅ PASS' if qc.homodimer_ok else '⚠️ FAIL'}")
            lines.append(f"- Heterodimer: {'✅ PASS' if qc.heterodimer_ok else '⚠️ FAIL'}")
            lines.append(f"- Tm Balance: {'✅ PASS' if qc.tm_balance_ok else '⚠️ FAIL'} (Δ{qc.tm_diff:.2f}°C)")
            lines.append("")
            
            # Warnings
            if qc.warnings:
                lines.append("### Warnings")
                for warning in qc.warnings:
                    lines.append(f"- ⚠️ {warning}")
                lines.append("")
            
            # Errors
            if qc.errors:
                lines.append("### Errors")
                for error in qc.errors:
                    lines.append(f"- ❌ {error}")
                lines.append("")
        else:
            lines.append("⚠️ **No QC data available**")
            lines.append("")
        
        # Footer
        lines.append("---")
        lines.append("")
        lines.append("*Generated by PrimerLab qPCR Workflow*")
        
        return "\n".join(lines)
